---
title: "05_analysis_1"
format: html
editor: visual
---

1.  **Raw data normalization**

```{r}
library(DESeq2)
library(readxl)

GSE182951 <- read_excel("Downloads/GSE182951_Counts_All_Samples.xlsx")
#View(GSE182951)
GSE182951 <- as.data.frame(GSE182951)
col <- as.data.frame(colnames(GSE182951)[-c(1:2)])
rownames(GSE182951) <- GSE182951$Name
Identifier <- GSE182951$Identifier
Name <- GSE182951$Name
GSE182951 <- GSE182951[, -c(1:2)]

dds <- DESeqDataSetFromMatrix(countData = GSE182951, colData = col, ~factor(c(rep("pCR", 12), rep("non-pCR", 28))))
dds <- DESeq(dds)
normalized_counts <- counts(dds, normalized = TRUE)
test <- data.frame("Name" = Name, "Identifier" = Identifier)
GSE182951_normalized <- cbind(test, normalized_counts)
rownames(GSE182951_normalized) <- 1:dim(GSE182951_normalized)[1]
save(GSE182951_normalized, file = "GSE182951_normalized.RData")
```

2.  **Differential expression analysis**

```{r}
library(DESeq2)
library(readxl)

load("~/r_for_bio_data_science/group_08_project/group_08_project/data/GSE182951_normalized.RData")
GSE182951 <- GSE182951_normalized
col <- as.data.frame(colnames(GSE182951)[-c(1:2)])
rownames(GSE182951) <- GSE182951$Name
Identifier <- GSE182951$Identifier
Name <- GSE182951$Name
GSE182951 <- GSE182951[, -c(1:2)]

#I. pCR non-pCR
dds <- DESeqDataSetFromMatrix(countData = GSE182951, colData = col, ~factor(c(rep("pCR", 12), rep("non-pCR", 28))))
dds <- DESeq(dds)

GSE182951_diff <- results(dds, alpha = 0.05)
GSE182951_diff_df <- as.data.frame(GSE182951_diff)
GSE182951_diff_genes <- rownames(filter(GSE182951_diff_df, padj < 0.05))

#II. pCR: pre pos  non-PCR: pre pos
GSE182951_pCR <- GSE182951[, 1:12]
GSE182951_non_pCR <- GSE182951[, 13:40]

col_pCR <- as.data.frame(colnames(GSE182951)[1:12])
col_non_pCR <- as.data.frame(colnames(GSE182951)[13:40])
dds_pCR <- DESeqDataSetFromMatrix(countData = GSE182951_pCR, colData = col_pCR, ~factor(c(rep(c("pre", "post"), 6))))
dds_non_pCR <- DESeqDataSetFromMatrix(countData = GSE182951_non_pCR, colData = col_non_pCR, ~factor(c(rep(c("pre", "post"), 14))))

dds_pCR <- DESeq(dds_pCR)
dds_non_pCR <- DESeq(dds_non_pCR)

GSE182951_diff_pCR_pre_post <- as.data.frame(results(dds_pCR, alpha = 0.05))
GSE182951_diff_nonpCR_pre_post <- as.data.frame(results(dds_non_pCR, alpha = 0.05))

GSE182951_diff_pCR_pre_post_genes <- rownames(filter(GSE182951_diff_pCR_pre_post, log2FoldChange > 1 | log2FoldChange < -1)) 
GSE182951_diff_nonpCR_pre_post_genes <- rownames(filter(GSE182951_diff_nonpCR_pre_post, log2FoldChange > 1 | log2FoldChange < -1))
```
